ALTER TABLE dbo.Stages
ADD 
	CONSTRAINT FK_BUILDING_STAGES FOREIGN KEY (IDbuilding) REFERENCES dbo.Building (IDbuilding);

ALTER TABLE dbo.Faculty
ADD
	CONSTRAINT FK_BUILDING_FACULTRY FOREIGN KEY(IDbuilding) REFERENCES dbo.Building (IDbuilding);

ALTER TABLE dbo.Room
ADD
	CONSTRAINT FK_ROOM_BUILDING FOREIGN KEY(IDbuilding) REFERENCES dbo.Building(IDbuilding),
	CONSTRAINT FK_ROOM_STAGES FOREIGN KEY(IDstage) REFERENCES dbo.Stages(IDstage);

ALTER TABLE dbo.Lab
ADD
	CONSTRAINT FK_STAGES_LAB FOREIGN KEY(IDstage) REFERENCES dbo.STAGES(IDstage);

ALTER TABLE dbo.Departament
ADD
	CONSTRAINT FK_DEPARTAMENT_LAB FOREIGN KEY(LabN) REFERENCES dbo.Lab(LabN);

ALTER TABLE dbo.Departament
ADD 
	CONSTRAINT FK_FACULTY_DEPARTAMENT FOREIGN KEY(IDfacultry) REFERENCES dbo.Faculty(IDfacultry);
