ALTER TABLE dbo.Building
ADD 
	CONSTRAINT FK_BUILDING_FACULTY FOREIGN KEY (IDbuilding) REFERENCES dbo.Faculty (IDbuilding) ON DELETE CASCADE;

ALTER TABLE dbo.Stages
ADD
	CONSTRAINT FK_STAGES_BUILDING FOREIGN KEY(IDbuilding) REFERENCES dbo.Building (IDbuilding) ON DELETE CASCADE;

ALTER TABLE dbo.Room
ADD
	CONSTRAINT FK_ROOM_BUILDIN FOREIGN KEY(IDbuilding) REFERENCES dbo.Building(IDbuilding),
	CONSTRAINT FK_ROOM_STAGES FOREIGN KEY(IDstage) REFERENCES dbo.Stages(IDstage) ON DELETE CASCADE;

ALTER TABLE dbo.Lab
ADD
	CONSTRAINT FK_STAGES_LAB FOREIGN KEY(IDstage) REFERENCES dbo.STAGES(IDstage) ON DELETE CASCADE;

ALTER TABLE dbo.Departament
ADD
	CONSTRAINT FK_DEPARTAMENT_LAB FOREIGN KEY(LabN) REFERENCES dbo.Lab(LabN) ON DELETE CASCADE;

ALTER TABLE dbo.Faculty
ADD 
	CONSTRAINT FK_FACULTY_DEPARTAMENT FOREIGN KEY(nameFacultry) REFERENCES dbo.Departament(nameFacultry) ON DELETE CASCADE;
